### ISSUE TITLE
Input Font is not white in Dark mode for ReactSelect

### ISSUE THREAD

**Issue by dpills** [vkumov/react-cui-2.0#3]
The input font for the `ReactSelect` component in Dark Mode is still dark and not readable. The font for the `react-select__input-container` class needs to be overridden. Adding it to the patched react css seems to fix the issue.

```css
.cui
  .react-select-container
  .react-select__control
  .react-select__value-container
  .react-select__single-value 
  .react-select__input-container {
  color: var(--cui-font-color);
}
```

Current
<img width="302" alt="Screenshot 2022-12-11 at 11 59 21 AM" src="https://user-images.githubusercontent.com/25569432/206917693-4da858ba-9504-47ac-bfb1-4ed551f0361e.png">

With updated CSS
<img width="302" alt="Screenshot 2022-12-11 at 11 59 06 AM" src="https://user-images.githubusercontent.com/25569432/206917696-86c6329d-e186-44d7-a0a3-c272ea6875bf.png">
